version: '3'

services:
  app:
    tty: true
    container_name: bbs
    build: .
    command: bundle exec rackup config.ru -p 5000 -o 0.0.0.0
    volumes:
      - .:/bbs
    ports:
      - 5000:5000
  db:
    image: postgres:10
    environment:
      POSTGRES_USER: sinatra
      POSTGRES_PASSWORD: sinatra
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
