CREATE DATABASE bbs;
\c bbs;

CREATE TABLE IF NOT EXISTS board (
  id SERIAL NOT NULL PRIMARY KEY,
  name VARCHAR( 25 ) NOT NULL,
  email VARCHAR( 25 ) NOT NULL,
  message VARCHAR( 25 ) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
  id SERIAL NOT NULL PRIMARY KEY ,
  name VARCHAR( 25 ) NOT NULL ,
  email VARCHAR( 35 ) NOT NULL ,
  password VARCHAR( 60 ) NOT NULL ,
  UNIQUE (email)
);
